"use client";
import React from "react";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";
import Footer from "../common/footer";
import { STATIC_LINKS } from "@/constants/static-links";

const containerVariants = {
    hidden: { opacity: 0 },
    show: {
        opacity: 1,
        transition: { staggerChildren: 0.1, delayChildren: 0.1 },
    },
};

const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring" as const, stiffness: 300, damping: 25 } },
};


const TermsAndConditionsPageComp: React.FC = () => {
    return (
        <div className="min-h-screen bg-background text-foreground relative overflow-hidden flex flex-col">
            <div className="dot-grid fixed inset-0 pointer-events-none opacity-[0.4] z-0" />
            <div
                className={cn(
                    "absolute inset-0 pointer-events-none z-0",
                    "bg-[radial-gradient(ellipse_800px_600px_at_top_center,var(--color-secondary))_0%,transparent_80%]"
                )}
            />

            <div className="h-30 shrink-0 w-full relative z-10" />

            <main className="relative z-10 grow flex flex-col items-center justify-center pb-24 px-6">
                <motion.div
                    initial="hidden"
                    animate="show"
                    variants={containerVariants}
                    className="w-full max-w-[1000px] flex flex-col gap-12"
                >
                    <motion.div variants={itemVariants} className="mt-8 mb-4">
                        <h1 className="font-black tracking-tighter text-5xl sm:text-7xl text-foreground" style={{ fontFamily: "system-ui, -apple-system, sans-serif" }}>
                            Terms and <span className="text-primary">Conditions.</span>
                        </h1>
                        <p className="mt-6 text-muted-foreground text-lg font-medium">Last updated: May 2026</p>
                    </motion.div>

                    <motion.div variants={itemVariants} className="text-xl text-foreground leading-relaxed font-medium border-l-2 border-primary pl-6">
                        <p>By accessing or using <strong>Just Pick Already</strong> at justpickalready.in, you agree to these terms. If you do not agree, please do not use the site.</p>
                    </motion.div>

                    <div className="h-px bg-border/60 w-full" />

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">1. What This Is</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>Just Pick Already is a free, anonymous personality game for entertainment purposes only. The personality results generated by this game are produced by an AI model and are not a substitute for professional psychological assessment, therapy, or medical advice. Results are meant to be fun and reflective, not clinical or definitive.</p>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">2. Use of the Service</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>You may use Just Pick Already for personal, non-commercial purposes. You agree not to:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Attempt to reverse engineer, scrape, or interfere with the site or its API routes</li>
                                <li>Use automated tools to generate sessions in bulk</li>
                                <li>Use the site for any unlawful purpose</li>
                            </ul>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">3. Intellectual Property</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>All content on this site including the game design, text, and code is owned by Just Pick Already. The open-source codebase is available on GitHub under the MIT licence. You may not reproduce or redistribute site content without permission.</p>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">4. AI-Generated Content</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>Game scenarios and personality results are generated by Google's Gemini AI model. We do not guarantee the accuracy, completeness, or appropriateness of any AI-generated content. Results vary per session and should not be taken as factual assessments of your personality.</p>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">5. Third Party Services</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>This site uses third-party services including Supabase and Vercel. We are not responsible for the privacy practices or content of those services.</p>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">6. Disclaimer of Warranties</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>Just Pick Already is provided as-is without warranties of any kind. We do not guarantee uninterrupted availability, error-free operation, or that the site will meet your expectations.</p>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">7. Limitation of Liability</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>To the fullest extent permitted by applicable law, Just Pick Already and its creator shall not be liable for any indirect, incidental, or consequential damages arising from your use of this site.</p>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">8. Governing Law</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>These terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in India.</p>
                        </div>
                    </motion.section>

                    <motion.section variants={itemVariants}>
                        <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground mb-4">9. Contact</h2>
                        <div className="text-lg text-muted-foreground leading-relaxed space-y-4">
                            <p>For any questions about these terms, contact us at: <code className="text-foreground bg-muted px-2 py-1 rounded-md text-base">{STATIC_LINKS.email}</code></p>
                        </div>
                    </motion.section>

                </motion.div>
            </main>

            <div className="relative z-10 w-full mt-auto">
                <Footer />
            </div>
        </div>
    );
};

export default TermsAndConditionsPageComp;
