export { default as HeroSection } from '@/components/home/sections/hero-sec'
export { default as MapSection } from '@/components/home/sections/map-sec'
export { default as PreviewSections } from '@/components/home/sections/preview-sec'
export { default as HowToPlaySection } from '@/components/home/sections/how-to-play-sec'
export { default as ResultCardSection } from '@/components/home/sections/result-card-sec'
export { default as ZoneSections } from '@/components/home/sections/zone-sec'
export { default as EndCardSection } from '@/components/home/sections/end-card-sec'