import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import "@/src/style/globals.css";
import AppProvider from "@/src/provider";
import { cn } from "@heroui/react";
import Header from "@/src/components/layouts/header";

const dmSans = DM_Sans({ 
  subsets: ['latin'],
  variable: '--font-dm-sans',
  weight: ['400', '500', '600', '700']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("light", dmSans.className)}>
      <body>
        <AppProvider>
          <div className="flex flex-col w-full">
            <Header />  
            <main className="flex-1 bg-background text-foreground">
              {children}
            </main>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
