import type { Metadata } from "next";
import { DM_Sans, Geist } from 'next/font/google';
import { Analytics } from "@vercel/analytics/next"

import AppProvider from "@/provider";
import { cn } from "@/lib/utils";
import "@/style/globals.css";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const dmSans = DM_Sans({ 
  subsets: ['latin'],
  variable: '--font-dm-sans',
  weight: ['400', '500', '600', '700']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("light", dmSans.className, "font-sans", geist.variable)}>
      <body>
        <Analytics />
        <AppProvider>
          <div className="flex flex-col w-full">
            <main className="flex-1 bg-background text-foreground">
              {children}
            </main>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
