import type { Metadata } from "next";
import { DM_Sans, Geist } from 'next/font/google';
import { Analytics } from "@vercel/analytics/next"
import { cn } from "@/lib/utils";
import "@/style/globals.css";

import AppProvider from "@/provider";
import Header from "@/components/common/header";
import OnbordingHandler from "@/components/home/onbording-handler";
import { Toaster } from "@/components/ui/sonner";


const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const dmSans = DM_Sans({ 
  subsets: ['latin'],
  variable: '--font-dm-sans',
  weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("light", dmSans.className, "font-sans", geist.variable)}>
      <body>
        <Analytics />
        <AppProvider>
          <div className="flex flex-col w-full">
            <Header />
            <main className="flex-1 bg-background text-foreground">
              {children}
              <OnbordingHandler />
            </main>
          </div>
          <Toaster position="top-right" />
        </AppProvider>
      </body>
    </html>
  );
}
